# Site
favicon: images/favicon(1).ico

# Content configuration version
version: 2

# Personal info
name: Harikrishnan Sreekumar, M.Sc.
title: Computational Researcher
email: hk.sreekumar@icloud.com
website: https://hksreekumar.github.io/profile/

# Dark Mode (true/false/never)
darkmode: true

# Social links
linkedin_username: hksreekumar
github_username:  hksreekumar
instagram_username: harikrishnan_hkks
orcid_username: 0000-0001-9803-7968

# Additional icon links
additional_links:
- title: ResearchGate
  icon: fab fa-researchgate
  url: https://www.researchgate.net/profile/Harikrishnan-K-Sreekumar

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
google_analytics: G-VKYTELGFBC
google_site_verification: _nFGPGIAoZhF300eX0YmKZd6kZZsDivsyOS9e4YIiuA

# About Section
about_title: About
about_profile_image: images/hk.jpg
about_content: | 
  Hi! I am Harikrishnan Sreekumar born on November 1993 in Kerala, India. Currently I live in Braunschweig, Germany to acquire my doctoral degree.
  
  I am a computational researcher specialized in the research of efficient numerical methods and solving strategies. Experienced with developing high performance numerical softwares in a sustainable manner, also designing from scratch, to handle solving algorithms for sophisticated problems by deploying high-end parallel programming methodologies and model order reduction techniques so as to reduce large-scale dimension of computational models. In addition, I am greatly fascinated by codes that are pushing the actual scientific limits.

  My interests: <br/>
  <mark>Numerical methods</mark> <mark>Algorithms</mark> <mark>C++</mark> <mark>Data-driven methods</mark> <mark>Dimensionality reduction</mark> <mark>High performance computing</mark><br/>
  <mark>Computational code development</mark> <mark>Quantum computing</mark> <mark>Digital twins</mark>

  *Get in touch!*
content:
  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top
        title: Technische Universit√§t Braunschweig | Institute for Acoustics and Dynamics, Germany
        link: https://www.tu-braunschweig.de/ina/institut/team/harikrishnan-k-sreekumar
        link_text: tu-braunschweig.de
        sub_title: Research associate
        caption: February 2019 - Present
        description: | 
            - Since August 2023 - Research coordinator for the InAD Research Field "Physics-based Modelling and Simulations"
            - Doctoral research on parametric surrogate modeling of high-dimensional vibroacoustic problems using projection-based model order reduction
            - Enabled efficient computation of expensive multi-physic aircraft simulations for various fuselage designs using faster (heavy) data management, optimized solvers and parametric reduced order models
            - Lead developer and contact person for the in-house high-performance computing C++ software project
            - Managed C++ and python software projects (with approx. 300000 lines of code and 8 active developers)
            - Raised the quality of the computational codes as a project member of SURESOFT: Sustainable Research Software Development and Deployment
            - Other key activities: advised 7 master thesis projects, assisted master courses, lectured 3 seminar talks, presented work in 7 international conferences, published 12 research papers, 2 software publications and conducted 4~dynamic workshops related to scientific software development (252 participants) 
      - layout: top
        title: BMW Group, Munich | Research, New Technologies, Innovations
        sub_title: Master Thesis Intern
        caption: June 2018 - December 2018
        description: | 
            - Thesis work on Krylov subspace model order reduction in vibroacoustics
      - layout: top
        title: BMW Group, Munich | Research, New Technologies, Innovations
        sub_title: Research Intern
        caption: November 2017 - June 2018
        description: | 
            - Developed a C++ tool for model order reduction and application to automotive problems like the BMW i7 rear axle model for vibroacoustic analysis
            - Implemented advanced algorithms using math routines with Intel Math Kernel Library (MKL) and visualization of simulated data with Qt and Visualization Toolkit (VTK)
            - Built finite element routine for steady-state dynamic systems with fluid-structure interaction, various boundary conditions and distributed load coupling
      - layout: top
        title: Technische Universit√§t Braunschweig | Institute for Engineering Design
        sub_title: Student research assistant
        caption: June 2016 - October 2017
        description: | 
            - Acoustic simulation of various geometries for static, frequency and time domain analysis
            - Maintained a high-performance computing C++ FEM code for better performance and maintenance of software dependencies (MPI, PETSc, SLEPc, ARPACK, HDF5)
            - Development of an uncertainty quantification module in python

  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top
        title: Doctor of Engineering (Dr.-Ing.) in Mechanical Engineering / Computational Sciences
        sub_title: Technische Universit√§t Braunschweig
        caption: February 2019 - Present (expected completion by mid 2024)
        description: |
            - Successfully submitted dissertation titled  "Surrogate modelling of high-dimensional vibroacoustic problems using parametric model order reduction" and application to large-scale novel aircraft design concepts
            - Dimensionality reduction techniques
            - Techniques for efficient solving of large-scale mechanical systems

      - layout: top
        title: Master of Science (M. Sc.) in Computational Sciences in Engineering
        sub_title: Technische Universit√§t Braunschweig
        caption: October 2015 - December 2018
        description: |
            - Master thesis: Krylov-based model order reduction in vibroacoustics 
            - Student project: Transmission loss calculations of aircraft fuselage structures
            - Main subjects: Finite element method, Computational acoustics, Linear continuum mechanics, Contact mechanics, Advanced object oriented C++ techniques, Partial differential equations, Ordinary differential equations
            - Other subjects: Algorithms and programming, Isogeometric analysis, Computational aeroacoustics

      - layout: top
        title: Bachelor of Technology in Mechanical Engineering
        sub_title: University of Kerala, India
        caption: September 2011 - April 2015
        description: | 
            - Main subjects: Design of Machine Elements, Heat and Mass Transfer, Dynamics of Machinery, Theory of Machines, Refrigeration and Air Conditioning, Mechatronics, Gas Dynamics, Non Destructive Testing, Automobile Engineering, Thermal Engineering, Fluid Mechanics & Machines, Thermodynamics
  - title: Publications # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        quote: >
          For latest publications visit my profile on ResearchGate
        description: |
          **Research papers** 
          - C. Blech, H. K. Sreekumar, Y. H√ºpel, S. C. Langer: Efficient solution strategies for cabin noise assessment of a wave resolving aircraft fuselage model. ArXiV preprint. DOI: [10.48550/arXiv.2310.04734](https://doi.org/10.48550/arXiv.2310.04734). 2023.
          - Y. H√ºpel, C. Blech, H. K. Sreekumar, S. C. Langer: Efficient solutions of preconditioned large‚Äêscale systems for simulative aircraft cabin noise assessment. In: Proceedings in Applied Mathematics and Mechanics. DOI: [10.1002/pamm.202300102](https://doi.org/10.1002/pamm.202300102). 2023.
          - H. K. Sreekumar, L. Outzen, U. R√∂mer and S. C. Langer: Clustering-based parametric surrogate modeling of vibroacoustic problems assisted by neural networks and active subspace method, in: Adaptive modeling and simulation (ADMOS) 2023. DOI: [10.23967/admos.2023.009](https://doi.org/10.23967/admos.2023.009)
          - H. K. Sreekumar, C. Blech, S. C. Langer: Sustainable development and deployment of an acoustic FEM research software. In: Proceedings of DAGA 2023, Hamburg, Germany. 2023.
          - H. K. Sreekumar, Y. H√ºpel, and S. C. Langer: Active subspace realization for accelerated training of parametric reduced-order models in vibroacoustics. In Proceedings of the ICA 2022, Gyeongju, Korea, 2022.
          - C. Blech, N. Dreyer, B. Friebel, C. R. Jacob, M. Shamil Jassim, L. Jehl, R. Kapitza, M. Krafczyk, T. K√ºrner, S. C. Langer, J. Linxweiler, M.Mahhouk, S.Marcus, I.Messadi, S. Peters, J.-M. Pilawa, H. K. Sreekumar, R. Str√∂tgen, K. Stump, A. Vogel, M. Wolter: SURESOFT: Towards Sustainable Research Software. In: campusSOURCE Award 2022. 2022. DOI: [10.24355/dbbs.084-202210121528-0](https://doi.org/10.24355/dbbs.084-202210121528-0)
          - L. Hermann, H. K. Sreekumar, S. C. Langer, U. R√∂mer: A statistical approach for the fusion of data and finite element analysis in vibroacoustics, In: Proceedings of DAGA 2022, Pages 895-898, Stuttgart. 2022.
          - U. R√∂mer, M. Bollh√∂fer, H. K. Sreekumar, C. Blech, and S. C. Langer: An adaptive sparse grid rational arnoldi method for uncertainty quantification of dynamical systems in the frequency domain. International Journal for Numerical Methods in Engineering, DOI: [10.1002/nme.6761](https://doi.org/10.1002/nme.6761), 2021.
          - C. Blech, H. K. Sreekumar, U. R√∂mer, M. Bollh√∂fer, S. C. Langer: Ein adaptives hybrides Verfahren zur Modellordnungsreduktion von dynamischen Systemen im Frequenzbereich. In: Proceedings of DAGA 2021, Vienna, Austria. 2021.
          - H. K. Sreekumar, R. Ullmann, S. Sicklinger, S. C. Langer: Efficient Krylov subspace techniques for model order reduction of automotive structures in vibroacoustic applications. In: Model Reduction of Complex Dynamical Systems. International Series of Numerical Mathematics, vol 171. Birkh√§user, Cham. DOI: [10.1007/978-3-030-72983-7_12](https://doi.org/10.1007/978-3-030-72983-7_12). 2021.
          - H. K. Sreekumar, C. Blech, S. C. Langer: Large-scale vibroacoustic simulations using parallel direct solvers for high-performance clusters. In: Proceedings of DAGA 2021, Vienna, Austria. 2021.
          - Y. H√ºpel, H. K. Sreekumar, S. C. Langer:  Pole-Matching Technique for Parametric Model Order Reduction of Second Order Vibroacoustic Systems. In: Proceedings of DAGA 2021, Vienna, Austria. 2021.

          **Software publications**
          - H. K. Sreekumar: elPaSo AcMoRe - Python module for faster training and evaluation of vibroacoustic systems with model order reduction. DOI: [10.24355/dbbs.084-202301301305-0](https://doi.org/10.24355/dbbs.084-202403151156-0). 2024.
          - H. K. Sreekumar, S. C. Langer: elPaSo Research - Elementary parallel solver research module for high performance vibroacoustic simulations. DOI: [10.24355/dbbs.084-202403151154-0](https://doi.org/10.24355/dbbs.084-202403151154-0). 2024.
          - H. K. Sreekumar, S. C. Langer: elPaSo Core - Elementary parallel solver core module for high performance vibroacoustic simulations. DOI: [10.24355/dbbs.084-202301301305-0](https://doi.org/10.24355/dbbs.084-202301301305-0). 2023.
          - H. K. Sreekumar, C. Blech, S. C. Langer: elPaSo AUTOMATE - Automated testing framework for validation and verification of a vibroacoustic simulation tool. DOI: [10.24355/dbbs.084-202301301258-0](https://doi.org/10.24355/dbbs.084-202301301258-0). 2023.

          **Dataset publications**
          - H. K. Sreekumar: Dataset for the study of frequency-domain model order reduction techniques in vibroacoustic applications. DOI: [10.24355/dbbs.084-202403151158-0](https://doi.org/10.24355/dbbs.084-202403151158-0). 2024.
          - H. K. Sreekumar: Dataset for the study of various error measures steering adaptive model order reduction algorithms in vibroacoustic applications. DOI: [10.24355/dbbs.084-202403151201-0](https://doi.org/10.24355/dbbs.084-202403151201-0). 2024.
          - H. K. Sreekumar: Dataset for the study of parametric-domain model order reduction techniques in vibroacoustic applications. DOI: [10.24355/dbbs.084-202403151200-0](https://doi.org/10.24355/dbbs.084-202403151200-0). 2024.
          - H. K. Sreekumar, S. C. Langer: Benchmark dataset for verification and validation of elPaSo Core module. DOI: [10.5281/zenodo.7612532](https://doi.org/10.5281/zenodo.7612532). [Zenodo] 2023.
  
  - title: Misc activities
    layout: list
    content:
      - layout: top-middle
        description: | 
          **Certifications**
          - Certified Junior Project Manager, IAPM International Association of Project Managers
          - German language certification, Deutsche Sprachpr√ºfung f√ºr den Hochschulzugang (DSH); DSH-2 certified

          **Conducted workshops**
          - [Online] Workshop for HeFDI (Hessian Research Data Infrastructures) Code School in November 2023 - Introduction to software testing - Unit testing, acceptance testing, code-quality checks and test automation. # participants: 94. DOI: [10.5281/zenodo.10185185](https://doi.org/10.5281/zenodo.10185185)
          - [Online] Workshop for HeFDI (Hessian Research Data Infrastructures) Code School in June 2023 - Introduction to software testing - Unit testing, acceptance testing, code-quality checks and test automation. # participants: 72. DOI: [10.5281/zenodo.8069918](https://doi.org/10.5281/zenodo.8069918)
          - [Online] Workshop for TU Braunschweig in August 2022: Suresoft workshop series - Introduction to software testing - Unit testing, acceptance testing, code-quality checks and test automation. # participants: 47. DOI: [10.24355/dbbs.084-202212141407-0](https://doi.org/10.24355/dbbs.084-202212141407-0)
          - [Online] Workshop for TU Braunschweig in September 2022: Suresoft workshop series - Introduction to Continuous Integration (CI) with GitLab and Containerization with Docker. # participants: 39. DOI: [10.24355/dbbs.084-202212141353-0](https://doi.org/10.24355/dbbs.084-202212141353-0)

          **Teaching activities**
          - Lecture on "Modelling of complex systems / Modellierung komplexe Systeme" for bachelor course Digitalisation in Aerospace Engineering (Digitalisierung Luft und Raumfahrtechnik). April, 2024.
          - Lecture on "Data and Code Management" for bachelor course Digitalisation in Aerospace Engineering (Digitalisierung Luft und Raumfahrtechnik). April, 2024.
          - Teaching assistant for master course "Computational Acoustics". 2024.
          - Teaching assistant for master course "Computational Acoustics". 2023.
          - Teaching assistant for master course "Computational Acoustics". 2022.
          - Teaching assistant for master course "Computational Acoustics". 2021.
          - Teaching assistant for master course "Computational Acoustics". 2020.
          - Teaching assistant for master course "Computational Acoustics". 2019.

          **Other talks/invited lectures**
          - Error-controlled local interpolation of moment matching reduced order models for vibroacoustics. Invited talk in minisymposium "Error-Controlled Adaptive Algorithms in Full-Order and Reduced-Order Model Simulations". International Congress on Industrial and Applied Mathematics (ICIAM) 2023, Waseda University, Tokyo, Japan.
          - Machine-Learning and efficient computational models in acoustics. TU Braunschweig lecture series Fascination Acoustics in summer semester 2021.

          **Supervised theses**
          - Sustainable software development through continuous integration considering high-performance computing aspects in vibroacoustics. Master Thesis. 2024.
          - Low-rank approximation based separate bases reduction approaches for coupled vibroacoustic models. Student Project. 2023.
          - A statistical approach for the fusion of data and finite element analysis in vibroacoustics. Master Thesis. 2021.
          - Pole-matching technique for parametric model order reduction of second-order vibroacoustic systems. Master Thesis. 2021.
          - Efficient parameterization of vibroacoustic models for model order reduction. Student Project. 2020.
          - Modal projection techniques for model order reduction of vibroacoustic systems. Student Project. 2020.
          - Finite element based approach on defining standards and benchmarks for an automated testing environment. Student Project. 2020.
  
  - title: Hobbies
    layout: list
    content:
      - layout: top-middle
        description: | 
          Cycling üö¥, padel tennis üéæ, photography üì∑, travelling ‚úàÔ∏è

          *Follow my instagram handle for my favorite pictures ;)*

# Footer
footer_show_references: false

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
